https://colab.research.google.com/drive/18Taq2vemfhwCRC4yodRODPWDWRqUiduk?usp=sharing$0

In [4]:
import numpy as np

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
print(f"stores : {stores}\n")
print(f"categories : {categories}\n")
print(f"sales_data :\n {sales_data}\n")
print(f"cost_data : \n {cost_data}\n")

stores : ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

categories : ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

sales_data :
 [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

cost_data : 
 [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]



In [5]:
total_number_of_stores = len(stores)
total_number_of_categories = len(categories)
print(f"total_number_of_stores : {total_number_of_stores}\n")
print(f"total_number_of_categories : {total_number_of_categories}\n")

total_number_of_stores : 5

total_number_of_categories : 6



In [6]:
print(np.shape(sales_data))
print(sales_data.dtype)


(5, 6)
int64


In [7]:
x =sales_data.astype(float)
x
x.dtype


dtype('float64')

In [8]:
print(f"sales_for_bangalore :{ sales_data[0,0:]}\n")
print(f"mumbai_Store_cost_analysis : {cost_data [3,0:]}")

sales_for_bangalore :[850000 420000 310000 275000 190000 225000]

mumbai_Store_cost_analysis : [790000 390000 265000 250000 165000 205000]


In [9]:
print(f"elcectronics_sales :\n {sales_data[0:,:1]}\n")
print(f"cloathing_cost : \n{cost_data[0:,2:3]}")


elcectronics_sales :
 [[ 850000]
 [ 780000]
 [ 920000]
 [1050000]
 [ 690000]]

cloathing_cost : 
[[220000]
 [210000]
 [245000]
 [265000]
 [205000]]


In [10]:
#hydrabad furniture performance
Hydrabad_furniture_performance = sum(sales_data[1:2,0:]) - sum(cost_data[1:2,0:])
print(f"Hydrabad_furniture_profit : {Hydrabad_furniture_performance}\n")




Hydrabad_furniture_profit : [190000 110000  85000  85000  70000  70000]



In [11]:
# Extract Chennai’s sales for the following categories:
# Groceries
# Clothing
# Furniture
groceries_sales = sales_data[2,1]
cloathing_sales = sales_data[2,2]
furniture_sales = sales_data[2,3]
print(f"chennai_groceries_sales : {groceries_sales}\n")
print(f"chennai_cloathing_sales : {cloathing_sales}\n")
print(f"chennai_furniture_sales : {furniture_sales}\n")

print(f"chennai_GCF_sales : {sales_data[2,1:4]})")

chennai_groceries_sales : 390000

chennai_cloathing_sales : 340000

chennai_furniture_sales : 260000

chennai_GCF_sales : [390000 340000 260000])


In [12]:
# Extract sales data for:
# Bengaluru
# Chennai
# Pune
# ######Include only:
# Electronics
# Clothing
# Beauty
Bangalore_sales_for_ECB =sales_data[0,[0,2,4]]
chenai_sales_for_ECB = sales_data[2,[0,2,4]]
Pune_sales_for_ECB = sales_data[4,[0,2,4]]
print(f"Bangalore_sales_for_ECB : {Bangalore_sales_for_ECB}\n")
print(f"chenai_sales_for_ECB : {chenai_sales_for_ECB}\n")
print(f"Pune_sales_for_ECB : {Pune_sales_for_ECB}\n")

Bangalore_sales_for_ECB : [850000 310000 190000]

chenai_sales_for_ECB : [920000 340000 185000]

Pune_sales_for_ECB : [690000 280000 175000]



In [13]:
#Calculate the total sales revenue generated by all stores and all categories.
total_blore_sales =sum(sales_data[0,0:])
total_hydrabad_sales =sum(sales_data[1,0:])
total_chennai_sales =sum(sales_data[2,0:])
total_mumbai_sales =sum(sales_data[3,0:])
total_pune_sales =sum(sales_data[4,0:])
print(f"total_blore_sales : {total_blore_sales}\n")
print(f"total_hydrabad_sales : {total_hydrabad_sales}\n")
print(f"total_chennai_sales : {total_chennai_sales}\n")
print(f"total_mumbai_sales : {total_mumbai_sales}\n")
print(f"total_pune_sales : {total_pune_sales}\n")


total_blore_sales : 2270000

total_hydrabad_sales : 2295000

total_chennai_sales : 2310000

total_mumbai_sales : 2820000

total_pune_sales : 1980000



In [14]:
sum([850000, 420000, 310000, 275000, 190000, 225000])

2270000

In [15]:
total_elctronics_sales =sum(sales_data[0:,0])
total_groceries_sales =sum(sales_data[0:,1])
total_cloathing_sales =sum(sales_data[0:,2])
total_furniture_sales =sum(sales_data[0:,3])
total_beauty_sales =sum(sales_data[0:,4])
total_sports_sales =sum(sales_data[0:,5])
print(f"total_elctronics_sales : {total_elctronics_sales}\n")
print(f"total_groceries_sales : {total_groceries_sales}\n")
print(f"total_cloathing_sales : {total_cloathing_sales}\n")
print(f"total_furniture_sales : {total_furniture_sales}\n")
print(f"total_beauty_sales : {total_beauty_sales}\n")
print(f"total_sports_sales : {total_sports_sales}\n")

total_elctronics_sales : 4290000

total_groceries_sales : 2185000

total_cloathing_sales : 1600000

total_furniture_sales : 1415000

total_beauty_sales : 1010000

total_sports_sales : 1175000



In [16]:
#Average Sales Per Store/ catagerioes

In [17]:
blore_avg_sales = total_blore_sales/total_number_of_categories
hydrabad_avg_sales = total_hydrabad_sales/total_number_of_categories
chennai_avg_sales = total_chennai_sales/total_number_of_categories
mumbai_avg_sales = total_mumbai_sales/total_number_of_categories
pune_avg_sales = total_pune_sales/total_number_of_categories

print(f"blore_avg_sales : {blore_avg_sales}\n")
print(f"hydrabad_avg_sales : {hydrabad_avg_sales}\n")
print(f"chennai_avg_sales : {chennai_avg_sales}\n")
print(f"mumbai_avg_sales : {mumbai_avg_sales}\n")
print(f"pune_avg_sales : {pune_avg_sales}\n")

blore_avg_sales : 378333.3333333333

hydrabad_avg_sales : 382500.0

chennai_avg_sales : 385000.0

mumbai_avg_sales : 470000.0

pune_avg_sales : 330000.0



In [18]:
np.mean(sales_data[0])

np.float64(378333.3333333333)

In [19]:
avg_sales_electronics = np.mean(sales_data[:,0])
avg_sales_groceries = np.mean(sales_data[:,1])
avg_sales_cloathing = np.mean(sales_data[:,2])
avg_sales_furniture = np.mean(sales_data[:,3])
avg_sales_beauty = np.mean(sales_data[:,4])
avg_sales_sports = np.mean(sales_data[:,5])
print(f"avg_sales_electronics : {avg_sales_electronics}\n")
print(f"avg_sales_groceries : {avg_sales_groceries}\n")
print(f"avg_sales_cloathing : {avg_sales_cloathing}\n")
print(f"avg_sales_furniture : {avg_sales_furniture}\n")
print(f"avg_sales_beauty : {avg_sales_beauty}\n")
print(f"avg_sales_sports : {avg_sales_sports}\n")

avg_sales_electronics : 858000.0

avg_sales_groceries : 437000.0

avg_sales_cloathing : 320000.0

avg_sales_furniture : 283000.0

avg_sales_beauty : 202000.0

avg_sales_sports : 235000.0



In [20]:
#Highest-Selling Category
x = np.array ([[np.mean(sales_data[:,0])],[np.mean(sales_data[:,1])],[np.mean(sales_data[:,2])],
 [np.mean(sales_data[:,3])],[np.mean(sales_data[:,4])],[np.mean(sales_data[:,5])]])
print(f"maximum sales of catageries :\n {x}")

maximum sales of catageries :
 [[858000.]
 [437000.]
 [320000.]
 [283000.]
 [202000.]
 [235000.]]


In [21]:
heighest_selling_category = np.max(x)
for i in range(0,6):
  if x[i] == heighest_selling_category:
    print(f"heighest_selling_category : {categories[i]}")
print(f"heighest_selling_price : {heighest_selling_category}")

heighest_selling_category : Electronics
heighest_selling_price : 858000.0


In [22]:
lowest_selling_category = np.min(x)
for i in range(0,6):
  if x[i] == lowest_selling_category:
    print(f"lowest_selling_category : {categories[i]}")
print(f"lowest_selling_price : {lowest_selling_category}")

lowest_selling_category : Beauty
lowest_selling_price : 202000.0


In [23]:
#Highest-Selling Store
y = np.array ([[sum(sales_data[0,0:])],
              [sum(sales_data[1,0:])],
              [sum(sales_data[2,0:])],
              [sum(sales_data[3,0:])],
              [sum(sales_data[4,0:])]])
y

array([[2270000],
       [2295000],
       [2310000],
       [2820000],
       [1980000]])

In [24]:
heighest_selling_store = np.max(y)
for i in range(0,5):
  if y[i] == heighest_selling_store:
    print(f"heighest_selling_store : {stores[i]}")
print(f"heighest_selling_price : {heighest_selling_store}")

heighest_selling_store : Mumbai
heighest_selling_price : 2820000


In [25]:
lowest_selling_store = np.min(y)
for i in range(0,5):
  if y[i] == lowest_selling_store:
    print(f"lowest_selling_store : {stores[i]}")
print(f"lowest_selling_price : {lowest_selling_store}")


lowest_selling_store : Pune
lowest_selling_price : 1980000


In [26]:
#Total Company Cost
cost_data

array([[640000, 315000, 220000, 205000, 125000, 160000],
       [590000, 350000, 210000, 225000, 140000, 170000],
       [700000, 295000, 245000, 195000, 120000, 155000],
       [790000, 390000, 265000, 250000, 165000, 205000],
       [530000, 310000, 205000, 170000, 115000, 145000]])

In [27]:
catagory_cost = sum(cost_data)
print(f"catagory_cost : {catagory_cost}")

catagory_cost : [3250000 1660000 1145000 1045000  665000  835000]


In [28]:
total_comapny_cost = sum(catagory_cost)
print(f"total_comapny_cost : {total_comapny_cost}")

total_comapny_cost : 8600000


In [29]:
#Store-Wise Cost
store_wise_cost = sum(cost_data[0,0:]),sum(cost_data[1,0:]),sum(cost_data[2,0:]),sum(cost_data[3,0:]),sum(cost_data[4,0:])
for i in range(0,5):
  print(f"\n{stores[i]}_cost_data : {store_wise_cost[i]}")



Bengaluru_cost_data : 1665000

Hyderabad_cost_data : 1685000

Chennai_cost_data : 1710000

Mumbai_cost_data : 2065000

Pune_cost_data : 1475000


In [30]:
store_wise_cost

(np.int64(1665000),
 np.int64(1685000),
 np.int64(1710000),
 np.int64(2065000),
 np.int64(1475000))

In [31]:
print(f"Most Expensive Store : {max(store_wise_cost)}")
print(f"low cost store : {min(store_wise_cost)}")

Most Expensive Store : 2065000
low cost store : 1475000


In [32]:
total_blore_sales

np.int64(2270000)

In [33]:
#category wise cost
category_wise_cost = np.array ([[sum(cost_data[0:,0])],[sum(cost_data[0:,1])],[sum(cost_data[0:,2])],[sum(cost_data[0:,3])],[sum(cost_data[0:,4])],[sum(cost_data[0:,5])]])
for i in range(0,6):
  print(f"\n{categories[i]}_cost_data : {category_wise_cost[i]}")

print(category_wise_cost)




Electronics_cost_data : [3250000]

Groceries_cost_data : [1660000]

Clothing_cost_data : [1145000]

Furniture_cost_data : [1045000]

Beauty_cost_data : [665000]

Sports_cost_data : [835000]
[[3250000]
 [1660000]
 [1145000]
 [1045000]
 [ 665000]
 [ 835000]]


In [34]:
print(f"Most Expensive Product Category : {max(category_wise_cost)}")
print(f"low cost Product Category : {min(category_wise_cost)}")

Most Expensive Product Category : [3250000]
low cost Product Category : [665000]


In [35]:
total_elctronics_sales

np.int64(4290000)

In [36]:
Hydrabad_furniture_performance

array([190000, 110000,  85000,  85000,  70000,  70000])

In [37]:
profit_data = sales_data - cost_data
profit_data

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

In [38]:
for i in range(0,5):
  print(f"\n{stores[i]}_profit_data : {profit_data[i,0:]}")
  print(f"\ntotal_{stores[i]}_profit : {sum(profit_data[i,0:])}")


Bengaluru_profit_data : [210000 105000  90000  70000  65000  65000]

total_Bengaluru_profit : 605000

Hyderabad_profit_data : [190000 110000  85000  85000  70000  70000]

total_Hyderabad_profit : 610000

Chennai_profit_data : [220000  95000  95000  65000  65000  60000]

total_Chennai_profit : 600000

Mumbai_profit_data : [260000 120000 110000  95000  85000  85000]

total_Mumbai_profit : 755000

Pune_profit_data : [160000  95000  75000  55000  60000  60000]

total_Pune_profit : 505000


In [39]:
for i in range(0,5):
  print(f"\n{categories[i]}_profit_data : {profit_data[0:,i]}")
  print(f"\ntotal_{categories[i]}_profit_data : {sum(profit_data[0:,i])}")



Electronics_profit_data : [210000 190000 220000 260000 160000]

total_Electronics_profit_data : 1040000

Groceries_profit_data : [105000 110000  95000 120000  95000]

total_Groceries_profit_data : 525000

Clothing_profit_data : [ 90000  85000  95000 110000  75000]

total_Clothing_profit_data : 455000

Furniture_profit_data : [70000 85000 65000 95000 55000]

total_Furniture_profit_data : 370000

Beauty_profit_data : [65000 70000 65000 85000 60000]

total_Beauty_profit_data : 345000


In [40]:
#Most Profitable Store

In [41]:
sum(profit_data[0,0:])

np.int64(605000)

In [42]:
p = np.array ([[sum(profit_data[0,0:])],[sum(profit_data[1,0:])],[sum(profit_data[2,0:])],[sum(profit_data[3,0:])],[sum(profit_data[4,0:])]])
p

array([[605000],
       [610000],
       [600000],
       [755000],
       [505000]])

In [43]:
print(f"Most Profitable Store : {max(p)}")
print(f"lowest Profitable store : {min(p)}")

Most Profitable Store : [755000]
lowest Profitable store : [505000]


In [44]:
q = np.array ([sum(profit_data[0:,0]),sum(profit_data[0:,1]),sum(profit_data[0:,2]),sum(profit_data[0:,3]),sum(profit_data[0:,4]),sum(profit_data[0:,5])])
q

array([1040000,  525000,  455000,  370000,  345000,  340000])

In [45]:
print(f"Most Profitable Category : {max(q)}")
print(f"low cost Product Category : {min(q)}")

Most Profitable Category : 1040000
low cost Product Category : 340000


In [46]:
profit_data

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

In [47]:
sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [48]:
cost_data


array([[640000, 315000, 220000, 205000, 125000, 160000],
       [590000, 350000, 210000, 225000, 140000, 170000],
       [700000, 295000, 245000, 195000, 120000, 155000],
       [790000, 390000, 265000, 250000, 165000, 205000],
       [530000, 310000, 205000, 170000, 115000, 145000]])

In [49]:
profit_percentage = (profit_data/cost_data)*100
print(profit_percentage)

[[32.8125     33.33333333 40.90909091 34.14634146 52.         40.625     ]
 [32.20338983 31.42857143 40.47619048 37.77777778 50.         41.17647059]
 [31.42857143 32.20338983 38.7755102  33.33333333 54.16666667 38.70967742]
 [32.91139241 30.76923077 41.50943396 38.         51.51515152 41.46341463]
 [30.18867925 30.64516129 36.58536585 32.35294118 52.17391304 41.37931034]]


In [50]:
#33 np.unravel_index().
np.argmax(profit_data)
#print(np.unravel_index(profit_data,(3,1)))

np.int64(18)

In [51]:
profit_data.flat[18]

np.int64(260000)

In [52]:
#Part 7: Profit Margin Analysis
profit_margin = (profit_data / sales_data)*100
print(f"profit_margin_perc : \n {profit_margin}")

profit_margin_perc : 
 [[24.70588235 25.         29.03225806 25.45454545 34.21052632 28.88888889]
 [24.35897436 23.91304348 28.81355932 27.41935484 33.33333333 29.16666667]
 [23.91304348 24.35897436 27.94117647 25.         35.13513514 27.90697674]
 [24.76190476 23.52941176 29.33333333 27.53623188 34.         29.31034483]
 [23.1884058  23.45679012 26.78571429 24.44444444 34.28571429 29.26829268]]


In [53]:
print(np.max(profit_margin))
print(np.argmax(profit_margin))

35.13513513513514
16


In [54]:
np.min(profit_margin)

np.float64(23.18840579710145)

In [55]:
np.max(profit_percentage)

np.float64(54.166666666666664)

In [56]:
profit_margin_stores = sum(profit_margin[0,0:]),sum(profit_margin[1,0:]),sum(profit_margin[2,0:]),sum(profit_margin[3,0:]),sum(profit_margin[4,0:])
for i in range(0,5):
  print(f"profit_margin_{stores[i]}: {profit_margin_stores[i]}")
#print(profit_margin_stores)

profit_margin_Bengaluru: 167.29210107668112
profit_margin_Hyderabad: 167.0049319979788
profit_margin_Chennai: 164.25530618714464
profit_margin_Mumbai: 168.47122657158812
profit_margin_Pune: 161.42936161935808


In [57]:
print(max(profit_margin_stores))
print(min(profit_margin_stores))

168.47122657158812
161.42936161935808


In [58]:
profit_margin_catgeories = sum(profit_margin[0 :,0]),sum(profit_margin[0 :,1]),sum(profit_margin[0 :,2]),sum(profit_margin[0 :,3]),sum(profit_margin[0 :,4]),sum(profit_margin[0 :,5])
for i in range(0,6):
  print(f"profit_margin_{categories[i]}: {profit_margin_catgeories[i]}")
#print(profit_margin_catgeories)

profit_margin_Electronics: 120.92821074918263
profit_margin_Groceries: 120.25821972539791
profit_margin_Clothing: 141.9060414761859
profit_margin_Furniture: 129.85457662175753
profit_margin_Beauty: 170.9647090699722
profit_margin_Sports: 144.54116981025464


In [59]:
print(max(profit_margin_catgeories))
print(min(profit_margin_catgeories))

170.9647090699722
120.25821972539791


In [60]:
#Low-Margin Transactions <24%
# Display:
# store
# Category
# Sales
# Cost
# Profit
# Profit margin

print(profit_margin[profit_margin<24])
print(" ")
for i in range(0,5):
  print(f"{stores[i]}_margin : {profit_margin[i,0:]<24}\n")

[23.91304348 23.91304348 23.52941176 23.1884058  23.45679012]
 
Bengaluru_margin : [False False False False False False]

Hyderabad_margin : [False  True False False False False]

Chennai_margin : [ True False False False False False]

Mumbai_margin : [False  True False False False False]

Pune_margin : [ True  True False False False False]



In [61]:
print(" ")
for i in range(0,6):
  print(f"{categories[i]}_margin : {profit_margin[0:,i]<24}\n")

 
Electronics_margin : [False False  True False  True]

Groceries_margin : [False  True False  True  True]

Clothing_margin : [False False False False False]

Furniture_margin : [False False False False False]

Beauty_margin : [False False False False False]

Sports_margin : [False False False False False]



In [62]:
x = profit_margin
x.T

array([[24.70588235, 24.35897436, 23.91304348, 24.76190476, 23.1884058 ],
       [25.        , 23.91304348, 24.35897436, 23.52941176, 23.45679012],
       [29.03225806, 28.81355932, 27.94117647, 29.33333333, 26.78571429],
       [25.45454545, 27.41935484, 25.        , 27.53623188, 24.44444444],
       [34.21052632, 33.33333333, 35.13513514, 34.        , 34.28571429],
       [28.88888889, 29.16666667, 27.90697674, 29.31034483, 29.26829268]])

In [63]:
#Find all sales values greater than ₹5,00,000 and less than 200000
x = sales_data[sales_data>500000]
print(x)
y = sales_data[sales_data<200000]
print(y)

[ 850000  780000  920000 1050000  510000  690000]
[190000 185000 175000]


In [64]:
#Find all store-category combinations where profit is greater than ₹1,50,000.
x = profit_data[profit_data>150000]
print(x)

[210000 190000 220000 260000 160000]


In [65]:
#Find sales values between ₹2,50,000 and ₹5,00,000.
x = sales_data[(sales_data>250000) & (sales_data<500000)]
print(x)
x = np.logical_and(sales_data>250000,sales_data<500000)
print(x)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 290000 405000 280000]
[[False  True  True  True False False]
 [False  True  True  True False False]
 [False  True  True  True False False]
 [False False  True  True False  True]
 [False  True  True False False False]]


In [66]:
# A store-category combination is considered premium when:
# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.
x = np.logical_and(sales_data>250000,profit_data<500000)
print(x)

[[ True  True  True  True False False]
 [ True  True  True  True False False]
 [ True  True  True  True False False]
 [ True  True  True  True False  True]
 [ True  True  True False False False]]


In [67]:
# Underperforming Combinations
# A store-category combination is considered underperforming when:
# Sales are below ₹2,50,000
# Profit margin is below 25%
x = np.logical_and(sales_data>250000,profit_margin<25)
print(x)

[[ True False False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]


In [68]:
# Question 47: Category Performance Classification

# Create a new array that classifies every sales value as:

# "High" when sales are at least ₹5,00,000
# "Medium" when sales are between ₹2,50,000 and ₹4,99,999
# "Low" when sales are below ₹2,50,000
np.where(sales_data>500000,"High",np.where(sales_data>499999,"Medium","Low"))

array([['High', 'Low', 'Low', 'Low', 'Low', 'Low'],
       ['High', 'Low', 'Low', 'Low', 'Low', 'Low'],
       ['High', 'Low', 'Low', 'Low', 'Low', 'Low'],
       ['High', 'High', 'Low', 'Low', 'Low', 'Low'],
       ['High', 'Low', 'Low', 'Low', 'Low', 'Low']], dtype='<U6')

In [69]:
#Target based analysis
sales_targets = np.array([
     800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
sales_targets

array([800000, 450000, 320000, 300000, 200000, 230000])

In [70]:
sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [71]:
store_cat_sales = sales_data - sales_targets
print(f"store_cat_sales : \n {store_cat_sales}")

store_cat_sales : 
 [[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [72]:
compare = sales_data > sales_targets
print(f"compare : \n {compare}")

compare : 
 [[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [73]:
#Calculate the number of categories in which each store achieved its target
count = np.zeros(6, dtype=int)
for i in range(0,6):
  count[i] = np.sum(sales_data[0:,i] > sales_targets[i])
  print(f"\ncount_{categories[i]} : {count[i]}")



count_Electronics : 3

count_Groceries : 2

count_Clothing : 2

count_Furniture : 2

count_Beauty : 2

count_Sports : 2


In [74]:
###Find the store that achieved the highest number of category targets.
print(np.max(store_cat_sales))
np.argmax(store_cat_sales)

250000


np.int64(18)

In [75]:
#Calculate how many stores achieved the target for each product category.
count = np.zeros(5, dtype=int)
for i in range(0,5):
  count[i] = np.sum(sales_data[i,0:] > sales_targets)
  print(f"\ncount_{stores[i]} : {count[i]}")


count_Bengaluru : 1

count_Hyderabad : 4

count_Chennai : 2

count_Mumbai : 6

count_Pune : 0


In [76]:
#Calculate the difference between actual sales and target sales for every store.
variance = (sales_data - sales_targets)/sales_data *100
print(f"variance : \n{variance}")

variance : 
[[  5.88235294  -7.14285714  -3.22580645  -9.09090909  -5.26315789
   -2.22222222]
 [ -2.56410256   2.17391304  -8.47457627   3.22580645   4.76190476
    4.16666667]
 [ 13.04347826 -15.38461538   5.88235294 -15.38461538  -8.10810811
   -6.97674419]
 [ 23.80952381  11.76470588  14.66666667  13.04347826  20.
   20.68965517]
 [-15.94202899 -11.11111111 -14.28571429 -33.33333333 -14.28571429
  -12.19512195]]


In [77]:
#Identify stores that failed to achieve the Electronics sales target.
stores_not_achive_ele_target = sales_data[0:,0] < sales_targets[0]
print(f"stores_not_achive_ele_target : {stores_not_achive_ele_target}")

stores_not_achive_ele_target : [False  True False False  True]


In [78]:
print(np.all(compare[0,0:]))
print(np.all(compare[1,0:]))
print(np.all(compare[2,0:]))
print(np.all(compare[3,0:]))
print(np.all(compare[4,0:]))



False
False
False
True
False


In [79]:
#Check whether any store achieved its target in all six product categories.
count = np.zeros(5, dtype=int)
for i in range(0,5):
  count[i] =  np.all(compare[i,0:])
  print(f"\ncount_{stores[i]} : {'yes' if count[i]>0 else 'no'}")



count_Bengaluru : no

count_Hyderabad : no

count_Chennai : no

count_Mumbai : yes

count_Pune : no


In [80]:
#Identify stores that achieved at least one category target
np.any(compare[0:,0:])

np.True_

In [81]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [82]:
sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [83]:
profit_data

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

In [84]:
discount_amount = sales_data * discount_rates
print(f"discount_amount : \n {discount_amount}")

discount_amount : 
 [[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [85]:
sales_after_discount = sales_data - discount_amount
print(f"sales_after_discount : \n {sales_after_discount}")

sales_after_discount : 
 [[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [86]:
sales_after_discount = sales_data * (1 -discount_rates)
sales_after_discount

array([[765000., 399000., 263500., 242000., 174800., 202500.],
       [702000., 437000., 250750., 272800., 193200., 216000.],
       [828000., 370500., 289000., 228800., 170200., 193500.],
       [945000., 484500., 318750., 303600., 230000., 261000.],
       [621000., 384750., 238000., 198000., 161000., 184500.]])

In [87]:
profit_after_discount = sales_data - sales_after_discount
print(f"profit_after_discount : \n {profit_after_discount}")

profit_after_discount : 
 [[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [88]:
profit_margine_after_discount = (profit_after_discount/sales_data)*100
print(f"profit_margine_after_discount : \n {profit_margine_after_discount}")

profit_margine_after_discount : 
 [[10.  5. 15. 12.  8. 10.]
 [10.  5. 15. 12.  8. 10.]
 [10.  5. 15. 12.  8. 10.]
 [10.  5. 15. 12.  8. 10.]
 [10.  5. 15. 12.  8. 10.]]


In [89]:
#Check whether any store-category combination becomes loss-making after discounts.
np.any(profit_margine_after_discount <0)

np.False_

In [90]:
#Calculate how much total revenue the company loses because of the proposed discounts.
loss_after_discount = profit_data - profit_after_discount
print(f"loss_after_discount : \n {loss_after_discount}")

loss_after_discount : 
 [[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [91]:
#Identify the store that loses the highest amount of revenue due to discounts.
np.max(loss_after_discount)

np.float64(155000.0)

In [92]:
#Calculate how much total revenue the company loses because of the proposed discounts.
np.sum(loss_after_discount)

np.float64(1928650.0)

In [93]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
tax_rates

array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])

In [94]:
#Calculate the tax collected on sales for each store and category.
sales_after_tax = sales_data * (1 + tax_rates)
print(f"sales_after_tax : \n {sales_after_tax}")

sales_after_tax : 
 [[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [95]:
x = sales_data * tax_rates
x

array([[153000.,  21000.,  37200.,  49500.,  34200.,  27000.],
       [140400.,  23000.,  35400.,  55800.,  37800.,  28800.],
       [165600.,  19500.,  40800.,  46800.,  33300.,  25800.],
       [189000.,  25500.,  45000.,  62100.,  45000.,  34800.],
       [124200.,  20250.,  33600.,  40500.,  31500.,  24600.]])

In [96]:
y = x+ sales_data
y

array([[1003000.,  441000.,  347200.,  324500.,  224200.,  252000.],
       [ 920400.,  483000.,  330400.,  365800.,  247800.,  268800.],
       [1085600.,  409500.,  380800.,  306800.,  218300.,  240800.],
       [1239000.,  535500.,  420000.,  407100.,  295000.,  324800.],
       [ 814200.,  425250.,  313600.,  265500.,  206500.,  229600.]])

In [97]:
#calculate the final customer billing value after adding tax.

In [98]:
final_bill_amount = sales_after_tax - discount_amount
print(f"final_bill_amount : \n {final_bill_amount}")

final_bill_amount : 
 [[ 918000.  420000.  300700.  291500.  209000.  229500.]
 [ 842400.  460000.  286150.  328600.  231000.  244800.]
 [ 993600.  390000.  329800.  275600.  203500.  219300.]
 [1134000.  510000.  363750.  365700.  275000.  295800.]
 [ 745200.  405000.  271600.  238500.  192500.  209100.]]


In [99]:
sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [100]:
#Calculate the total tax collected by each store.
np.sum(x[0,0:])

np.float64(321900.0)

In [101]:
for i in range(0,5):
  print(f"\n{stores[i]}_tax_collected : {np.sum(x[i,0:])}")
# np.sum(sales_after_tax[0,0:])


Bengaluru_tax_collected : 321900.0

Hyderabad_tax_collected : 321200.0

Chennai_tax_collected : 331800.0

Mumbai_tax_collected : 401400.0

Pune_tax_collected : 274650.0


In [102]:
#Calculate total tax collected for each category.
for i in range(0,6):
  print(f"\n{categories[i]}_tax_collected : {np.sum(x[0:,i])}")


Electronics_tax_collected : 772200.0

Groceries_tax_collected : 109250.0

Clothing_tax_collected : 192000.0

Furniture_tax_collected : 254700.0

Beauty_tax_collected : 181800.0

Sports_tax_collected : 141000.0


In [103]:
#Identify the store that contributes the highest tax amount.
np.max(x)

np.float64(189000.0)

In [104]:
#part 12 Question 70: Updated Pune Electronics Sales
#Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.
sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [105]:
updated_sales_data = sales_data.copy() #deep_copy
updated_sales_data[4,0] = 740000
updated_sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 740000,  405000,  280000,  225000,  175000,  205000]])

In [106]:
cost_data


array([[640000, 315000, 220000, 205000, 125000, 160000],
       [590000, 350000, 210000, 225000, 140000, 170000],
       [700000, 295000, 245000, 195000, 120000, 155000],
       [790000, 390000, 265000, 250000, 165000, 205000],
       [530000, 310000, 205000, 170000, 115000, 145000]])

In [107]:
#Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.
#Furniture costs increase by 12% for all stores.

updated_cost_data = cost_data.copy()
#updated_cost_data[0,4] = cost_data[0,4] * 0.08
for i in range(0,5):
  updated_cost_data[i,3] = cost_data[i,3] * (1-0.12)
  updated_cost_data[i,4] = cost_data[i,4] * (1-0.08)

updated_cost_data


array([[640000, 315000, 220000, 180400, 115000, 160000],
       [590000, 350000, 210000, 198000, 128800, 170000],
       [700000, 295000, 245000, 171600, 110400, 155000],
       [790000, 390000, 265000, 220000, 151800, 205000],
       [530000, 310000, 205000, 149600, 105800, 145000]])

In [108]:
sales_data_after_pune_closed = np.delete(updated_sales_data,4, axis=0)
sales_data_after_pune_closed

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000]])

In [109]:
cost_data_after_pune_closed = np.delete(updated_cost_data,4,axis =0)
cost_data_after_pune_closed

array([[640000, 315000, 220000, 180400, 115000, 160000],
       [590000, 350000, 210000, 198000, 128800, 170000],
       [700000, 295000, 245000, 171600, 110400, 155000],
       [790000, 390000, 265000, 220000, 151800, 205000]])

In [110]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
print(delhi_sales)
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
print(delhi_cost)

[880000 475000 330000 290000 215000 250000]
[665000 360000 235000 215000 145000 180000]


In [111]:
delhi_updated_sales_data = np.vstack((sales_data_after_pune_closed,delhi_sales))
delhi_updated_sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 880000,  475000,  330000,  290000,  215000,  250000]])

In [112]:
cost_data_after_pune_closed

array([[640000, 315000, 220000, 180400, 115000, 160000],
       [590000, 350000, 210000, 198000, 128800, 170000],
       [700000, 295000, 245000, 171600, 110400, 155000],
       [790000, 390000, 265000, 220000, 151800, 205000]])

In [113]:
delhi_updated_cost_data = np.vstack((cost_data_after_pune_closed,delhi_cost))
delhi_updated_cost_data

array([[640000, 315000, 220000, 180400, 115000, 160000],
       [590000, 350000, 210000, 198000, 128800, 170000],
       [700000, 295000, 245000, 171600, 110400, 155000],
       [790000, 390000, 265000, 220000, 151800, 205000],
       [665000, 360000, 235000, 215000, 145000, 180000]])

In [114]:
updated_stores = np.delete(stores,4,axis=0)
print(updated_stores)
updated_stores = np.append(updated_stores,'delhi')
print(updated_stores)



['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'delhi']


Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.



In [115]:
import numpy as np
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

In [116]:
print(home_appliance_sales)
print(home_appliance_cost)

[360000 325000 390000 420000 295000]
[265000 240000 285000 305000 225000]


In [117]:
updated_categories = np.append(categories, 'Home Appliances')
updated_categories

array(['Electronics', 'Groceries', 'Clothing', 'Furniture', 'Beauty',
       'Sports', 'Home Appliances'], dtype='<U15')

In [118]:
new_updated_sales_data = np.column_stack((delhi_updated_sales_data,home_appliance_sales))
print(f"new_updated_sales_data : \n {new_updated_sales_data}")
print("")
new_updated_cost_data = np.column_stack((delhi_updated_cost_data,home_appliance_cost))
print(f"new_updated_cost_data : \n {new_updated_cost_data}")


new_updated_sales_data : 
 [[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 880000  475000  330000  290000  215000  250000  295000]]

new_updated_cost_data : 
 [[640000 315000 220000 180400 115000 160000 265000]
 [590000 350000 210000 198000 128800 170000 240000]
 [700000 295000 245000 171600 110400 155000 285000]
 [790000 390000 265000 220000 151800 205000 305000]
 [665000 360000 235000 215000 145000 180000 225000]]


In [119]:
new_total_sales = np.zeros(5)
for i in range(0,5):
  new_total_sales[i] = np.sum(new_updated_sales_data[i,0:])
  print(f"\n new_total_sales_{updated_stores[i]} : {new_total_sales[i]}")



 new_total_sales_Bengaluru : 2630000.0

 new_total_sales_Hyderabad : 2620000.0

 new_total_sales_Chennai : 2700000.0

 new_total_sales_Mumbai : 3240000.0

 new_total_sales_delhi : 2735000.0


In [120]:
new_total_cost = np.zeros(5)
for i in range(0,5):
  new_total_cost[i] = np.sum(new_updated_cost_data[i,0:])
  print(f"\n new_total_cost_{updated_stores[i]} : {new_total_cost[i]}")



 new_total_cost_Bengaluru : 1895400.0

 new_total_cost_Hyderabad : 1886800.0

 new_total_cost_Chennai : 1962000.0

 new_total_cost_Mumbai : 2326800.0

 new_total_cost_delhi : 2025000.0


In [121]:
print(np.sort(new_total_cost))

[1886800. 1895400. 1962000. 2025000. 2326800.]


In [122]:
print(np.argsort(new_total_cost))

[1 0 2 4 3]


In [123]:
new_total_cost[new_total_cost.argsort()[::-1]]

array([2326800., 2025000., 1962000., 1895400., 1886800.])

In [124]:
print(np.sort(new_total_sales))

[2620000. 2630000. 2700000. 2735000. 3240000.]


In [125]:
print(np.argsort(new_total_sales))

[1 0 2 4 3]


In [126]:
new_total_sales[new_total_sales.argsort()[::-1]]

array([3240000., 2735000., 2700000., 2630000., 2620000.])

In [127]:
new_profit_data = new_updated_sales_data - new_updated_cost_data
new_profit_data

array([[210000, 105000,  90000,  94600,  75000,  65000,  95000],
       [190000, 110000,  85000, 112000,  81200,  70000,  85000],
       [220000,  95000,  95000,  88400,  74600,  60000, 105000],
       [260000, 120000, 110000, 125000,  98200,  85000, 115000],
       [215000, 115000,  95000,  75000,  70000,  70000,  70000]])

In [128]:
store_profit_data = np.sum(new_profit_data, axis=1)
for i in range(0,5):
  print(f"\n new_store_profit_data_{updated_stores[i]} : {store_profit_data[i]}")


 new_store_profit_data_Bengaluru : 734600

 new_store_profit_data_Hyderabad : 733200

 new_store_profit_data_Chennai : 738000

 new_store_profit_data_Mumbai : 913200

 new_store_profit_data_delhi : 710000


In [129]:
sort_profit = np.sort(store_profit_data)
sort_profit


array([710000, 733200, 734600, 738000, 913200])

In [130]:
new_total_cost[[-1, -2, -3]]

array([2025000., 2326800., 1962000.])

In [131]:
#Sort Categories by Revenue

In [132]:
new_total_categories_revenue = np.sum(new_updated_sales_data, axis=0)
for i in range(0,7):
  print(f"\n new_total_sales_{updated_categories[i]} : {new_total_categories_revenue[i]}")


 new_total_sales_Electronics : 4480000

 new_total_sales_Groceries : 2255000

 new_total_sales_Clothing : 1650000

 new_total_sales_Furniture : 1480000

 new_total_sales_Beauty : 1050000

 new_total_sales_Sports : 1220000

 new_total_sales_Home Appliances : 1790000


In [133]:
sort_categories = np.sort(new_total_categories_revenue)
sort_categories

array([1050000, 1220000, 1480000, 1650000, 1790000, 2255000, 4480000])

In [134]:
new_total_categories_revenue[new_total_categories_revenue.argsort()[::-1]]

array([4480000, 2255000, 1790000, 1650000, 1480000, 1220000, 1050000])

In [135]:
sort_sales = np.sort(new_total_sales)
sort_sales

array([2620000., 2630000., 2700000., 2735000., 3240000.])

In [136]:
#Top Three Store-Category Sales
print(f"top 3 store_catagory : \n {sort_categories[[-1,-2,-3]]}")
print(f"top 3 sales_catagory : \n {sort_sales[[-1,-2,-3]]}")


top 3 store_catagory : 
 [4480000 2255000 1790000]
top 3 sales_catagory : 
 [3240000. 2735000. 2700000.]


In [137]:
print(f"bottom 3 sales profit : \n {sort_profit[[1,2,3]]}")

bottom 3 sales profit : 
 [733200 734600 738000]


Part 14: Statistical Analysis
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

In [138]:
new_updated_sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000,  360000],
       [ 780000,  460000,  295000,  310000,  210000,  240000,  325000],
       [ 920000,  390000,  340000,  260000,  185000,  215000,  390000],
       [1050000,  510000,  375000,  345000,  250000,  290000,  420000],
       [ 880000,  475000,  330000,  290000,  215000,  250000,  295000]])

In [139]:
print(f"max: {np.max(new_updated_sales_data)}")
print(f"min: {np.min(new_updated_sales_data)}")
print(f"mean: {np.mean(new_updated_sales_data)}")
print(f"median: {np.median(new_updated_sales_data)}")
print(f"std: {np.std(new_updated_sales_data)}")
print(f"var: {np.var(new_updated_sales_data)}")
print(f"25th percentile: {np.percentile(new_updated_sales_data,25)}")
print(f"50th percentile: {np.percentile(new_updated_sales_data,50)}")
print(f"75th percentile: {np.percentile(new_updated_sales_data,75)}")
print(f"90th percentile: {np.percentile(new_updated_sales_data,90)}")

max: 1050000
min: 185000
mean: 397857.14285714284
median: 325000.0
std: 220746.4146749313
var: 48728979591.83672
25th percentile: 255000.0
50th percentile: 325000.0
75th percentile: 420000.0
90th percentile: 822000.0000000001


In [140]:
for i in range(0,5):
  print(f"{updated_stores[i]}_store_std = {np.std(new_updated_sales_data[i])}")


Bengaluru_store_std = 206612.62185598462
Hyderabad_store_std = 181195.01277094032
Chennai_store_std = 230781.7238899837
Mumbai_store_std = 252301.6497151368
delhi_store_std = 213866.2561279925


In [141]:
#Question 83: Category-Wise Standard Deviation
for i in range(0,7):
  print(f"{updated_categories[i]}_category_std = {np.std(new_updated_sales_data[0:,i])}")


Electronics_category_std = 89576.78270623476
Groceries_category_std = 42000.0
Clothing_category_std = 27386.127875258306
Furniture_category_std = 29563.490998188965
Beauty_category_std = 23021.728866442678
Sports_category_std = 25961.50997149434
Home Appliances_category_std = 44564.55991031438


uestion 84: Sales Above Company Average
Calculate the company-wide average sales value.
Count how many store-category sales values are above this average.

In [142]:
company_wide_average_sales = np.mean(new_updated_sales_data)
print(f"company_wide_average_sales : {company_wide_average_sales}")


company_wide_average_sales : 397857.14285714284


In [143]:
new_updated_sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000,  360000],
       [ 780000,  460000,  295000,  310000,  210000,  240000,  325000],
       [ 920000,  390000,  340000,  260000,  185000,  215000,  390000],
       [1050000,  510000,  375000,  345000,  250000,  290000,  420000],
       [ 880000,  475000,  330000,  290000,  215000,  250000,  295000]])

In [144]:
count = np.zeros(5)
for i in range(0,5):
  count[i] = np.sum(new_updated_sales_data[i,0:] > company_wide_average_sales)
count

array([2., 2., 1., 3., 2.])

In [145]:
high_value_outlier = np.mean(new_updated_sales_data) + 1.5*np.std(new_updated_sales_data)
high_value_outlier

np.float64(728976.7648695398)

In [146]:
# Treat any sales value greater than:
# as a high-value outlier.
# identify all such sales values.

In [147]:
import numpy as np
result = []
for i in range(0,5):
  for j in range(0,7):
    if (new_updated_sales_data[i,j] > high_value_outlier):
      result.append("yes")
    else:
      result.append('No')
print(np.array([result]).reshape(5,7))

[['yes' 'No' 'No' 'No' 'No' 'No' 'No']
 ['yes' 'No' 'No' 'No' 'No' 'No' 'No']
 ['yes' 'No' 'No' 'No' 'No' 'No' 'No']
 ['yes' 'No' 'No' 'No' 'No' 'No' 'No']
 ['yes' 'No' 'No' 'No' 'No' 'No' 'No']]


Reshaping and Transformation

Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

In [148]:
x = np.random.randint(0,100,(3,4))
print(x)
y[0] = 10
print(x)

[[66 25 84 88]
 [91  0 91 86]
 [41 48 66 22]]
[[66 25 84 88]
 [91  0 91 86]
 [41 48 66 22]]


In [149]:
x.flatten()

array([66, 25, 84, 88, 91,  0, 91, 86, 41, 48, 66, 22])

flatten() → COPY  → original is safe.  make deep copy
ravel()   → VIEW  → original may change make shallow copy

In [150]:
y = x.ravel()
print(x)
y[0] = 10
print(x)

[[66 25 84 88]
 [91  0 91 86]
 [41 48 66 22]]
[[10 25 84 88]
 [91  0 91 86]
 [41 48 66 22]]


Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2

In [151]:
x = np.random.randint(0,100,(5,6))
print(x)

[[33 53  4 95 98 81]
 [ 2 70  7  6 98 62]
 [79 71 44 65 26  7]
 [82 14 28 90 49 23]
 [21 19 23 90 24 50]]


In [152]:
print(x.reshape(3,10))
print("")
print(x.reshape(10,3))
print("")
print(x.reshape(15,2))
print("")
print(x.reshape(2,15))

[[33 53  4 95 98 81  2 70  7  6]
 [98 62 79 71 44 65 26  7 82 14]
 [28 90 49 23 21 19 23 90 24 50]]

[[33 53  4]
 [95 98 81]
 [ 2 70  7]
 [ 6 98 62]
 [79 71 44]
 [65 26  7]
 [82 14 28]
 [90 49 23]
 [21 19 23]
 [90 24 50]]

[[33 53]
 [ 4 95]
 [98 81]
 [ 2 70]
 [ 7  6]
 [98 62]
 [79 71]
 [44 65]
 [26  7]
 [82 14]
 [28 90]
 [49 23]
 [21 19]
 [23 90]
 [24 50]]

[[33 53  4 95 98 81  2 70  7  6 98 62 79 71 44]
 [65 26  7 82 14 28 90 49 23 21 19 23 90 24 50]]


In [153]:
print(sales_data)
print("")
j = sales_data.T
print(j)
print("")
print(j.shape)


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]

(6, 5)


Stack sales_data and cost_data vertically.

Display the resulting shape.

In [154]:
p = np.vstack((sales_data,cost_data))
print(p)
print(p.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.

In [155]:
k = np.stack((sales_data,cost_data),axis=0)
print(k)
print(k.shape)

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
(2, 5, 6)


In [156]:
k.ndim

3

Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

In [157]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values


In [158]:
np.count_nonzero(np.isnan(sales_with_missing))

4

In [159]:
np.where(np.isnan(sales_with_missing))

(array([0, 1, 3, 4]), array([2, 3, 1, 4]))

In [160]:
print(np.any(np.isnan(sales_with_missing), axis=0))
print(np.any(np.isnan(sales_with_missing) , axis =1))

[False  True  True  True  True False]
[ True  True False  True  True]


Replace Missing Values with Zero

Replace all missing sales values with zero.



In [161]:
x = np.nan_to_num(sales_with_missing,nan=0)
x

array([[ 850000.,  420000.,       0.,  275000.,  190000.,  225000.],
       [ 780000.,  460000.,  295000.,       0.,  210000.,  240000.],
       [ 920000.,  390000.,  340000.,  260000.,  185000.,  215000.],
       [1050000.,       0.,  375000.,  345000.,  250000.,  290000.],
       [ 690000.,  405000.,  280000.,  225000.,       0.,  205000.]])

Replace with Company Average

Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [162]:
x = np.nan_to_num(sales_with_missing,nan = np.round(np.nanmean(sales_with_missing),2))
x

array([[ 850000.  ,  420000.  ,  398846.15,  275000.  ,  190000.  ,
         225000.  ],
       [ 780000.  ,  460000.  ,  295000.  ,  398846.15,  210000.  ,
         240000.  ],
       [ 920000.  ,  390000.  ,  340000.  ,  260000.  ,  185000.  ,
         215000.  ],
       [1050000.  ,  398846.15,  375000.  ,  345000.  ,  250000.  ,
         290000.  ],
       [ 690000.  ,  405000.  ,  280000.  ,  225000.  ,  398846.15,
         205000.  ]])

Replace each missing value with the average sales value of its respective product category.

In [163]:
x = np.nan_to_num(sales_with_missing,nan = np.round(np.nanmean(sales_with_missing,axis =0),2))
x

array([[ 850000.,  420000.,  322500.,  275000.,  190000.,  225000.],
       [ 780000.,  460000.,  295000.,  276250.,  210000.,  240000.],
       [ 920000.,  390000.,  340000.,  260000.,  185000.,  215000.],
       [1050000.,  418750.,  375000.,  345000.,  250000.,  290000.],
       [ 690000.,  405000.,  280000.,  225000.,  208750.,  205000.]])

Missing Value Impact

Compare total sales before and after replacing missing values with zero.

In [164]:
x = np.sum(sales_with_missing)
x

np.float64(nan)

In [165]:
x = np.nan_to_num(sales_with_missing,nan=0)
x = np.sum(x)
x

np.float64(10370000.0)

Conditional Business Decisions

Question 96: Store Performance Labels

Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

In [166]:
sales_data

array([[ 850000,  420000,  310000,  275000,  190000,  225000],
       [ 780000,  460000,  295000,  310000,  210000,  240000],
       [ 920000,  390000,  340000,  260000,  185000,  215000],
       [1050000,  510000,  375000,  345000,  250000,  290000],
       [ 690000,  405000,  280000,  225000,  175000,  205000]])

In [167]:
total_sales = np.sum(sales_data)
total_sales

np.int64(11675000)

In [168]:
new_total_sales

conditions = [
    new_total_sales > 2800000,  # "Excellent": Total sales above ₹28,00,000
    (new_total_sales >= 2400000) & (new_total_sales <= 2800000), # "Good": Total sales between ₹24,00,000 and ₹28,00,000
    new_total_sales < 2400000   # "Needs Improvement": Total sales below ₹24,00,000
]

choices = [
    "Excellent",
    "Good",
    "Needs Improvement"
]

# np.select will return an array of classifications, one for each store
store_performance_classification = np.select(conditions, choices, default="Undefined")

for i in range(len(updated_stores)):
  print(f"\n{updated_stores[i]}_store_performance : {store_performance_classification[i]}")


Bengaluru_store_performance : Good

Hyderabad_store_performance : Good

Chennai_store_performance : Good

Mumbai_store_performance : Excellent

delhi_store_performance : Good


Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero


In [169]:
profit_data

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

In [170]:
conditions = [
    profit_data >=200000,
    (profit_data >= 100000) & (profit_data < 200000),
    profit_data < 100000,
    profit_data < 0
]

choices = [
    'Highly Profitable',
    'Profitable',
    'Low Profit',
    'Loss'
]


store_profit_classification = np.select(conditions, choices, default="Undefined")

for i in range(len(updated_stores)):
  print(f"\n{updated_stores[i]}_store_profit_classification : {store_profit_classification[i]}")


Bengaluru_store_profit_classification : ['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']

Hyderabad_store_profit_classification : ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']

Chennai_store_profit_classification : ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']

Mumbai_store_profit_classification : ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
 'Low Profit']

delhi_store_profit_classification : ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']


A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.



In [171]:
stores

array(['Bengaluru', 'Hyderabad', 'Chennai', 'Mumbai', 'Pune'], dtype='<U9')

In [172]:
total_store_sales = np.array([total_blore_sales,total_hydrabad_sales,total_chennai_sales,
                              total_mumbai_sales,total_pune_sales])
total_store_sales

array([2270000, 2295000, 2310000, 2820000, 1980000])

In [173]:
total_store_sales_profit = np.sum(profit_data,axis=1)
total_store_sales_profit


array([605000, 610000, 600000, 755000, 505000])

In [174]:
total_store_sale_PM = np.round((profit_margin*0.25) ,2)
print(total_store_sale_PM)
total_store_sale_PM = np.sum(total_store_sale_PM,axis=1)
print(total_store_sale_PM)

[[6.18 6.25 7.26 6.36 8.55 7.22]
 [6.09 5.98 7.2  6.85 8.33 7.29]
 [5.98 6.09 6.99 6.25 8.78 6.98]
 [6.19 5.88 7.33 6.88 8.5  7.33]
 [5.8  5.86 6.7  6.11 8.57 7.32]]
[41.82 41.74 41.07 42.11 40.36]


In [175]:
count = []
for i in range(0,5):
  if(total_store_sales[i] > 2500000 and total_store_sales_profit[i] > 700000 and total_store_sale_PM[i] > 25):
    count.append('eligible for expansion')
  else:
    count.append('not eligible for expansion')

print(np.array(count))

['not eligible for expansion' 'not eligible for expansion'
 'not eligible for expansion' 'eligible for expansion'
 'not eligible for expansion']


Part 18: Inventory Scenario

Use the following inventory arrays:

In [176]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Calculate closing stock using:

In [179]:
cloasing_stock = opening_stock - units_sold # unsold_stock
print(cloasing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Identify store-category combinations where closing stock is below 30 units.



In [ ]:
s = np.any(cloasing_stock < 30, axis=0)
print(s)

Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [ ]:
percentage_of_opening_stock = np.round((cloasing_stock/opening_stock)*100,2)
print(percentage_of_opening_stock)

Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.



In [ ]:
fast_moving_store_category_combinations = 100 - percentage_of_opening_stock
print(fast_moving_store_category_combinations)

In [ ]:
count =[]
for i in range(0,5):
  for j in range(0,6):
    if(fast_moving_store_category_combinations[i,j] > 80):
      count.append('fast moving')
    else:
      count.append('-*-')
print(np.array(count).reshape(5,6))


Category-Wise Units Sold

Calculate the total units sold for each product category.

In [ ]:
total_units_sold_for_each_product_category = np.sum(units_sold,axis=0)
print(total_units_sold_for_each_product_category)

# NumPy Retail Analytics Assignment
Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

In [ ]:
total_units_sold_for_each_product_store = np.sum(units_sold,axis=1)
print(total_units_sold_for_each_product_store)

Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.



In [ ]:
print(np.max(total_units_sold_for_each_product_store))
print(np.argmax(total_units_sold_for_each_product_store))

Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.



In [ ]:
np.where(cloasing_stock < 25,True,False)

Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.



In [ ]:
np.where(cloasing_stock < 25,True,0)

Advanced NumPy Questions

Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using np.cumsum().

In [ ]:
sales_data

In [ ]:
total_cumulative_sum_for_each_product_category = np.cumsum(sales_data,axis=0)
print(total_cumulative_sum_for_each_product_category)

In [ ]:
total_cumulative_sum_for_each_product_store = np.cumsum(sales_data,axis=1)
print(total_cumulative_sum_for_each_product_store)

Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

In [ ]:
x = sales_data.flatten()
print(x)
print("")
y = np.cumsum(x)
print(f"cumsum of sales_data : \n {y}")

Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using np.diff().



In [ ]:
p = np.diff(sales_data,axis=0)
print(p)
print(p.shape)

Question 113: Unique Sales Values

Find all unique sales values in sales_data.

Also count the frequency of each value.

In [ ]:
unique_values,counts = np.unique(sales_data , return_counts=True)
print(unique_values)
print(counts)

Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [ ]:
values = np.where(sales_data == 420000)
print(values)

Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [ ]:
boolean_array = np.where(sales_data > cost_data,True,False)
print(boolean_array)

In [ ]:
np.all(boolean_array>0)

Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [ ]:
profit_data

In [ ]:
np.clip(profit_data,75000,250000)

Normalize Sales Data

Normalize all sales values using min-max normalization:

In [ ]:
minimum = np.min(sales_data)
maximum = np.max(sales_data)

normalized = (sales_data - minimum) / (maximum - minimum)

print(normalized)




Question 118: Standardize Sales Data

Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [ ]:
Standardized_Sales  = (sales_data - np.mean(sales_data)) / np.std(sales_data)
print(Standardized_Sales)

Question 119: Round Values

Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [ ]:
np.round(profit_margin,2)

In [ ]:
profit_margin.astype(int)

In [ ]:
np.floor(profit_margin)

In [ ]:
np.ceil(profit_margin)

Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [ ]:
np.save('sales_data.npy',sales_data)
np.save('cost_data.npy',cost_data)
np.save('profit_data.npy',profit_data)

In [ ]:
np.load('sales_data.npy')

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value

In [188]:
print("Company Summary")
print("===============================================")
print(f"Total company sales : {np.sum(sales_data)}")
print(f"Total company cost : {np.sum(cost_data)}")
print(f"Total company profit : {np.sum(profit_data)}")
print(f"Overall company profit margin : {np.round(np.sum(profit_data)/np.sum(sales_data)*100,2)}%")
print(f"Average transaction value : {np.round(np.mean(sales_data),2)}")
print(f"Highest individual sales value : {np.max(sales_data)}")
print(f"Lowest individual sales value : {np.min(sales_data)}")
print("-------------------------------------------------------------------------")
print("Store Summary")
print("")
print(f"Total sales : {np.sum(sales_data)}")
print(f"Total cost : {np.sum(cost_data)}")
print(f"Total profit : {np.sum(profit_data)}")
print(f"Profit margin : {np.round(np.sum(profit_data)/np.sum(sales_data)*100,2)}%")
print(f"Total units sold : {np.sum(units_sold)}")
print(f"Expansion eligibility : {np.all(cloasing_stock < 30)}")
print("---------------------------------------------------")
print("Category Summary")
print("")
print(f"Total sales : {np.sum(sales_data)}")
print(f"Total cost : {np.sum(cost_data)}")
print(f"Total profit : {np.sum(profit_data)}")
print(f"Profit margin : {np.round(np.sum(profit_data)/np.sum(sales_data)*100,2)}%")
print(f"Average sales : {np.round(np.mean(sales_data),2)}")
print(f"Total units sold : {np.sum(units_sold)}")
print(f"store achived targets: {~stores_not_achive_ele_target}")


Company Summary
Total company sales : 11675000
Total company cost : 8600000
Total company profit : 3075000
Overall company profit margin : 26.34%
Average transaction value : 389166.67
Highest individual sales value : 1050000
Lowest individual sales value : 175000
-------------------------------------------------------------------------
Store Summary

Total sales : 11675000
Total cost : 8600000
Total profit : 3075000
Profit margin : 26.34%
Total units sold : 5720
Expansion eligibility : False
---------------------------------------------------
Category Summary

Total sales : 11675000
Total cost : 8600000
Total profit : 3075000
Profit margin : 26.34%
Average sales : 389166.67
Total units sold : 5720
store achived targets: [ True False  True  True False]


Store Summary

For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility

In [186]:
print("Store Summary")
print("")
print(f"Total sales : {np.sum(sales_data)}")
print(f"Total cost : {np.sum(cost_data)}")
print(f"Total profit : {np.sum(profit_data)}")
print(f"Profit margin : {np.round(np.sum(profit_data)/np.sum(sales_data)*100,2)}%")
print(f"Total units sold : {np.sum(units_sold)}")
print(f"Expansion eligibility : {np.all(cloasing_stock < 30)}")
print("---------------------------------------------------")
print("Category Summary")
print("")
print(f"Total sales : {np.sum(sales_data)}")
print(f"Total cost : {np.sum(cost_data)}")
print(f"Total profit : {np.sum(profit_data)}")
print(f"Profit margin : {np.round(np.sum(profit_data)/np.sum(sales_data)*100,2)}%")
print(f"Average sales : {np.round(np.mean(sales_data),2)}")
print(f"Total units sold : {np.sum(units_sold)}")
print(f"store achived targets: {~stores_not_achive_ele_target}")



Store Summary

Total sales : 11675000
Total cost : 8600000
Total profit : 3075000
Profit margin : 26.34%
Total units sold : 5720
Expansion eligibility : False
---------------------------------------------------
Category Summary

Total sales : 11675000
Total cost : 8600000
Total profit : 3075000
Profit margin : 26.34%
Average sales : 389166.67
Total units sold : 5720
store achived targets: [ True False  True  True False]
